services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      TZ: "UTC"
    volumes:
      - ./src:/var/www/html/public
      - ./php.ini:/usr/local/etc/php/conf.d/zz-custom.ini:ro
